/**

 * Row 46 — founder-approved Blueprint manuscript (recovered verbatim).

 * Generated by scripts/build-manuscript-from-sources.py — do not hand-edit generated/*.ts.

 */



import { aboutFounder } from "./generated/aboutFounder";

import { alivenessIndex } from "./generated/alivenessIndex";

import { architectsCommitment } from "./generated/architectsCommitment";

import { backHalfDeclaration } from "./generated/backHalfDeclaration";

import { backHalfStandards } from "./generated/backHalfStandards";

import { certificate } from "./generated/certificate";

import { chapter_1_awakening } from "./generated/chapter-1-awakening";

import { chapter_2_mirror } from "./generated/chapter-2-mirror";

import { chapter_3_decision } from "./generated/chapter-3-decision";

import { chapter_4_standards } from "./generated/chapter-4-standards";

import { chapter_5_architect } from "./generated/chapter-5-architect";

import { chapter_6_expansion } from "./generated/chapter-6-expansion";

import { chapter_7_beginning } from "./generated/chapter-7-beginning";

import { copyright } from "./generated/copyright";

import { decisionStatement } from "./generated/decisionStatement";

import { expansionPlan } from "./generated/expansionPlan";

import { founderClosing } from "./generated/founderClosing";

import { howToUse } from "./generated/howToUse";

import { architectIdentityStatement } from "./generated/architectIdentityStatement";

import { subtitle } from "./generated/subtitle";

import { title } from "./generated/title";

import { welcomeLetter } from "./generated/welcomeLetter";



export type ManuscriptBlock = {

  paragraphs?: readonly string[];

  lines?: readonly string[];

};



export type BlueprintManuscript = {

  title?: ManuscriptBlock;

  subtitle?: ManuscriptBlock;

  copyright?: ManuscriptBlock;

  welcomeLetter?: ManuscriptBlock;

  howToUse?: ManuscriptBlock;

  architectsCommitment?: ManuscriptBlock;

  chapters?: Partial<

    Record<

      | "chapter-1-awakening"

      | "chapter-2-mirror"

      | "chapter-3-decision"

      | "chapter-4-standards"

      | "chapter-5-architect"

      | "chapter-6-expansion"

      | "chapter-7-beginning",

      ManuscriptBlock

    >

  >;

  founderClosing?: ManuscriptBlock;

  aboutFounder?: ManuscriptBlock;

  artifacts?: Partial<

    Record<

      | "aliveness-index"

      | "decision-statement"

      | "back-half-standards"

      | "architect-identity-statement"

      | "expansion-plan"

      | "back-half-declaration",

      ManuscriptBlock

    >

  >;

  certificate?: ManuscriptBlock;

};



const manuscript: BlueprintManuscript = {

  title,

  subtitle,

  copyright,

  welcomeLetter,

  howToUse,

  architectsCommitment,

  chapters: {

    "chapter-1-awakening": chapter_1_awakening,

    "chapter-2-mirror": chapter_2_mirror,

    "chapter-3-decision": chapter_3_decision,

    "chapter-4-standards": chapter_4_standards,

    "chapter-5-architect": chapter_5_architect,

    "chapter-6-expansion": chapter_6_expansion,

    "chapter-7-beginning": chapter_7_beginning,

  },

  founderClosing,

  aboutFounder,

  artifacts: {

    "aliveness-index": alivenessIndex,

    "decision-statement": decisionStatement,

    "back-half-standards": backHalfStandards,

    "architect-identity-statement": architectIdentityStatement,

    "expansion-plan": expansionPlan,

    "back-half-declaration": backHalfDeclaration,

  },

  certificate,

};



export function getBlueprintManuscript(): BlueprintManuscript | null {

  return manuscript;

}



export function isManuscriptInserted(): boolean {

  return getBlueprintManuscript() !== null;

}


